url: http://ericdoerheit.github.io

# Site settings
title: Eric Dörheit
email: eric.doerheit@me.com
description: "My new homepage"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ericdoerheit
  - title: facebook
    url: http://www.facebook.com/jetgums
  - title: github
    url: http://github.com/ericdoerheit

# Postal address (add as many lines as necessary)
address:
  - line: Berlin

# Build settings
markdown: kramdown
permalink: pretty
